### ISSUE TITLE
Donator Rank

### ISSUE THREAD

**Issue by xM4G1CZz** [joshmoni/Joshmonis-Modpacks#10]
I bought a donator rank from this website: jmjp.buycraft.net

I don't know if it's the right donator or not, if it isn't would I be able to get it transfered?
And if it isn't and you won't allow a transfer can you send me the donator website?

**Comment by xM4G1CZz** [comment]
Oh and I play the middle earth one.

**Comment by xM4G1CZz** [comment]
Since today, the server was badly messed up. I lost my donator but managed
to get it back, I also lost my army (I spent atleast 17-20 stacks of coins
on the army) and most of them despawned. One last thing, checkpoints, I
lost the checkpoints around the place but I managed to set one at my base.
Please fix this and reply when possible
- Owen (x_M_4_G_1_C_Z_z)

**Comment by joshmoni** [comment]
Fixed the donator ranks just now...

As for the rest of the stuff, it seems to all be related to Middle-Earth. Last night, something went wrong on the server... dont know what, but it was fixed not too long ago. During the 8 hours of work i managed to succeed in: not losing the world or any progress; getting the server back online as soon as i could; and prevented a whole new reset.

The waypoints and stuff like that are beyond me, all i can say is sorry, but i didnt remove any files, nor did i purposely reset them. This probably wont happen again, but if it does, i will investigate further.

Not meaning to be angry at you, but you're the 4th person to confront me on this issue and must i remind all of you who asked, this is a quite heavily modded minecraft pack, and things are bound to go wrong. I didnt have to spend my day off fixing it today, but i did. I spend far too much time on this server and honestly wish for at least one day to be problem free!

I do hope this reply suits your needs, and in summary, nothing (expect donator stuff) will be replaced, mainly because its impossible to do so. And im sorry if you're at any loss.
- Joshmoni (sorry for any spelling or grammar errors - i didnt have time to read it through)
